# Generated by Django 2.1 on 2018-08-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
