# Generated by Django 2.0.7 on 2018-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
