# Generated by Django 2.0.7 on 2018-07-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20180719_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_resume', models.FileField(upload_to='uploads/temp/resume/%Y/%m/%d/')),
            ],
        ),
    ]
