# Generated by Django 2.0.5 on 2018-07-09 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
