# Generated by Django 2.0.7 on 2018-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_tempresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
