# Generated by Django 2.0.7 on 2018-07-10 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20180710_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to="'uploads/resume/%Y/%m/%d/'"),
            preserve_default=False,
        ),
    ]
