# Generated by Django 2.0.7 on 2018-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_parsedresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='applied_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
